FROM rust:1.90.0-alpine3.22 AS builder

RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static pkgconfig build-base curl git

ENV OPENSSL_STATIC=yes
ENV OPENSSL_LIB_DIR=/usr/lib
ENV OPENSSL_INCLUDE_DIR=/usr/include

WORKDIR /usr/src/app
COPY Cargo.toml Cargo.lock ./
COPY . .

RUN cargo build --release --bin nexusd
RUN strip target/release/nexusd

FROM alpine:3.22

RUN apk add --no-cache ca-certificates imagemagick imagemagick-webp imagemagick-heic imagemagick-svg imagemagick-jpeg imagemagick-tiff imagemagick-raw

COPY --from=builder /usr/src/app/target/release/nexusd /usr/local/bin/nexusd

RUN mkdir -p /data/static/files

COPY entrypoint-railway.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080 8081

CMD ["/entrypoint.sh"]
